nelmio_api_doc:
  documentation:
    info:
      title: Vinoteca 360
      description: You will need to log in via HTTP the first time you access the Swagger documentation (api/doc). After that, you won’t need to sign in again to make API requests. The “Authorize” button will still be visible, but you’ll only need it if you want to manually enter your JWT token.
      version: 1.0.2

    paths:
      /api/logout: ~

    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: [ ]

  areas: # to filter documented areas
    path_patterns:
      - ^/api
