nelmio_api_doc:
  documentation:
    info:
      title: Vinoteca 360
      description: You will need to log in when you first access the Swagger documentation (api/doc). Once you're signed in, you won't need to sign in again for API requests. The 'Authorize' button is there, but it has no functionality because we don't use tokens like JWT.
      version: 1.0.1

    paths:
        /api/logout: ~

    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: [ ]

  areas: # to filter documented areas
    path_patterns:
      - ^/api
